export const ADD_COUNT = 'add_count'
export const ADD_TO_CART = 'add_to_cart'
export const CHECK_CLICK = 'check_click'
export const CHECK_ALL = 'check_all'
export const NO_CHECK_ALL = 'no_check_click'
